spring:
  application:
    name: country-service
    
  cloud:
    config:
      enabled: true
      uri:
      - http://localhost:8888
#      profile: prod
  config:
    import:
    - optional:configserver:http://localhost:8888/
  profiles:
    active:
    - prod
  datasource:
    url: jdbc:h2:mem:test-me-country
    
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default: http://localhost:8761/eureka
    
country-service:
  code: us
  name: United States
server:
  port: 9090
 
 
resilience4j:
  retry:
    instances:
      retry-case:
        max-attempts: 5
        wait-duration: 10s
        enable-exponential-backoff: true
        enable-randomized-wait: true
        exponential-max-wait-duration: 10s
        
  circuitbreaker:
    instances:
      circuitbreaker-case:
        automatic-transition-from-open-to-half-open-enabled: true
        enable-exponential-backoff: true
        failure-rate-threshold: 50
        max-wait-duration-in-half-open-state: 15
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 5
        
        
        
        
        
        
        
        
        