spring:
  application:
    name: country-service
    
  cloud:
    config:
      enabled: true
      uri:
      - http://localhost:8888
#      profile: prod
  config:
    import:
    - optional:configserver:http://localhost:8888/
  profiles:
    active:
    - prod
eureka:
  client:
    enabled: false
    
country-service:
  code: us
  name: United States
  
 