spring:
  application:
    name: country-service
    
  cloud:
    config:
      enabled: true
      uri:
      - http://localhost:8888
  config:
    import:
    - optional:configserver:http://localhost:8888/
eureka:
  client:
    enabled: false
    
country-service:
  code: us
  name: United States
 
