# application level config
spring:
  application:
    name: continent-service

# cloud config 
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test-me-continent
  config:
    import:
    - optional:configserver:http://localhost:8888/
    
# server config
server:
  port: 8001
  
# Eureka Client config
eureka:
  client:
    enabled: true
    
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default: http://localhost:8761/eureka