# application level config
spring:
  application:
    name: continent-service

# cloud config 
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:test-me-continent
    
# server config
server:
  port: 8001
  
# Eureka Client config
eureka:
  client:
    enabled: false